### ISSUE TITLE
It is suggested to distinguish the size of the models.

### ISSUE THREAD

**Issue by daidaiershidi** [EnnengYang/Awesome-Model-Merging-Methods-Theories-Applications#1]
Thank you for bringing comprehensive work. Given the true practicality of merging methods, I would like to ask if you have considered distinguishing the size of models. For example, which methods are used for the integration of large models (at least greater than or equal to 7 billion)?

**Comment by EnnengYang** [comment]
Hi,

Your advice is very useful, and a clearer distinction between model sizes can help practitioners choose the appropriate model merging method.

In subsequent changes, I will consider adding details of the model sizes used in the paper, or explicitly flag papers that use model sizes 7B and above.

Thanks again, and if you have any other suggestions, please feel free to give us your feedback.

Sincerely,
Enneng

**Comment by daidaiershidi** [comment]
No suggestions, but one small question. Why does the same method show not only inconsistent performance in different papers, but also different trends in all of them? How to compare to get a specific method that works?

**Comment by EnnengYang** [comment]
Hi,

I think the following reasons may lead to different accuracies in different papers:
- Different checkpoints sources or fine-tuning strategies: Although the same dataset or model name, different training configurations (training steps/learning rates) will lead to obvious differences in fine-tuned weights, so the merging performance is different.
- Some model merging methods (such as RegMean, Fisher Merging, AdaMerging, etc.) have additional training processes, and the training configurations used (total data volume, batch size, optimizer configuration) also bring certain differences in results.

I think it is important to choose a fair experimental environment (same checkpoints, implementation platform) to compare various methods, such as [MergeKit](https://github.com/arcee-ai/mergekit), [FusionBench](https://github.com/tanganke/fusion_bench), etc.

Sincerely,
Enneng

**Comment by daidaiershidi** [comment]
Well, thanks for the reply.
